"""Use actual installed Codex TurnError shapes, not invented error fields.

Schema provenance: recovery-test-receipts/installed-appserver-error-schema.json,
generated by the installed codex app-server generate-json-schema command.
"""
import unittest

from control_supervisor import Supervisor


class ProtocolErrorAcceptance(unittest.TestCase):
    def test_response_stream_disconnection_is_a_transient_failure(self):
        for variant in ("responseStreamDisconnected", "responseStreamConnectionFailed"):
            with self.subTest(variant=variant):
                self.assertTrue(Supervisor._transient({
                    "message": "stream disconnected before completion",
                    "codexErrorInfo": {variant: {"httpStatusCode": None}},
                    "additionalDetails": None,
                }))

    def test_auth_quota_policy_and_unknown_are_not_transient_continuations(self):
        for info in ("unauthorized", "usageLimitExceeded", "rateLimitExceeded",
                     "sessionBudgetExceeded", "serverOverloaded", "cyberPolicy",
                     "misalignmentPolicyViolation", "badRequest", "other",
                     {"responseStreamConnectionFailed": {"httpStatusCode": 401}},
                     {"responseStreamConnectionFailed": {"httpStatusCode": 429}}):
            with self.subTest(info=info):
                self.assertFalse(Supervisor._transient({
                    "message": "provider returned an error", "codexErrorInfo": info,
                }))


if __name__ == "__main__":
    unittest.main()
